project:
  type: default
  execute-dir: project

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    toc-title: "Contents"
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    code-fold: true
    code-summary: "Show R code"
    code-tools: true
    embed-resources: true
    self-contained-math: true
    link-external-newwindow: true
    fig-responsive: true
    css: styles.css
